name: Build Helwan ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/local/share/boost
          sudo apt-get clean

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build ISO via Docker
        run: |
          mkdir -p out
          # تشغيل الدوكر مع تمرير المجلد الحالي كـ /repo
          docker run --privileged --rm \
            -v ${{ github.workspace }}:/repo \
            archlinux:latest \
            /bin/bash -c "
              pacman -Sy --noconfirm archlinux-keyring && \
              pacman -Syu --noconfirm archiso git && \
              sed -i 's/SigLevel    = Required DatabaseOptional/SigLevel = Optional TrustAll/g' /repo/pacman.conf && \
              sed -i '/^cheese$/d' /repo/packages.x86_64 && \
              mkarchiso -v -w /tmp/archiso-work -o /repo/out /repo
            "

      - name: Upload ISO
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Helwan-Linux-ISO
          path: out/*.iso
